name: ğŸ“± Gizmo Mobile App Build to Production

on:
  push:
    branches:
      - main

env:
  EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
  EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}

jobs:
  build:
    name: ğŸ macos-latest or ğŸŒ± ubuntu-latest
    runs-on: macos-latest
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v2

      - name: ğŸ‰ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.0.0
          cache: yarn

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸšª Log in to Expo
        run: npx expo login -u ${{ secrets.EXPO_CLI_USERNAME }} -p ${{ secrets.EXPO_CLI_PASSWORD }}
      
      - name: ğŸ“¦ Install expo
        run: yarn add expo

      - name: âš™ï¸ upgrade deb
        run:  npx expo install --check

      # - name: ğŸ§© install specific version
      #   run: |
      #     npm install @expo/config-plugins@6.0.0


      - name: ğŸ‰ Run expo-doctor
        run: npx expo-doctor

      - name: ğŸ‰ Build APK
        run: |
          eas build --profile preview --platform android

      - name: test job
        run:
          expo build:android --type apk --no-publish

      - name: ğŸ“¦ Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
